name: Document Generation
on:
  push:
    branches: 
      - master
jobs:
   docgen_and_pull_req:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - run: yarn docgen
       - name: Create pull request
         uses: peter-evans/create-pull-request@v3
         with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Adding Docs through yarn docgen
          title: YARN DOCGEN
