name: Issue commenting coz why not

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
    - uses: ben-z/actions-comment-on-issue@1.0.2
      with:
        message: "You gotsta be happy now owen"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

