name: learn-github-actions
on: [pull_request]
jobs:
  example:
    name: sample comment
    runs-on: ubuntu-latest
    steps:
      - name: comment PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Iz you Happy Owen"
          check_for_duplicate_msg: false  # OPTIONAL 


# on: [push]
# jobs:
#   check-bats-version:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#           node-version: "14"
#       - run: npm install -g bats
#       - run: bats -v
#       - name: Setup Node.js environment
#         uses: actions/setup-node@v2.4.0
#       - name: my stuff lol
#         run: ./temp.sh    
